PROJECT_ROOT    ?= $(PWD)
DOCKERFILE_PATH ?= $(CURDIR)/docker/Dockerfile
IMAGE_VERSION   ?= $(shell git describe --dirty=-unsupported --always --tags || echo pre-commit)

IMAGE_REGISTRY ?= amikhailau
IMAGE_NAME     ?= medieval-game-server
SERVER_IMAGE   := $(IMAGE_REGISTRY)/$(IMAGE_NAME)

GO_TEST_FLAGS  ?= -v -cover
GO_PACKAGES    := $(shell go list ./... | grep -v vendor)
